# Generated by Django 4.2.5 on 2024-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcheckout',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
